// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LongVector.proto

package edu.rice.pdb.serialization.proto;

public final class LongVectorProtos {
  private LongVectorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LongVectorPOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.rice.pdb.serialization.proto.LongVectorP)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required fixed64 position = 1;</code>
     */
    boolean hasPosition();
    /**
     * <code>required fixed64 position = 1;</code>
     */
    long getPosition();

    /**
     * <code>required double value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required double value = 2;</code>
     */
    double getValue();
  }
  /**
   * Protobuf type {@code edu.rice.pdb.serialization.proto.LongVectorP}
   */
  public static final class LongVectorP extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:edu.rice.pdb.serialization.proto.LongVectorP)
      LongVectorPOrBuilder {
    // Use LongVectorP.newBuilder() to construct.
    private LongVectorP(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LongVectorP(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LongVectorP defaultInstance;
    public static LongVectorP getDefaultInstance() {
      return defaultInstance;
    }

    public LongVectorP getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LongVectorP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              position_ = input.readFixed64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              value_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.rice.pdb.serialization.proto.LongVectorProtos.internal_static_edu_rice_pdb_serialization_proto_LongVectorP_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.rice.pdb.serialization.proto.LongVectorProtos.internal_static_edu_rice_pdb_serialization_proto_LongVectorP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP.class, edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP.Builder.class);
    }

    public static com.google.protobuf.Parser<LongVectorP> PARSER =
        new com.google.protobuf.AbstractParser<LongVectorP>() {
      public LongVectorP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LongVectorP(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LongVectorP> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int POSITION_FIELD_NUMBER = 1;
    private long position_;
    /**
     * <code>required fixed64 position = 1;</code>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required fixed64 position = 1;</code>
     */
    public long getPosition() {
      return position_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    /**
     * <code>required double value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double value = 2;</code>
     */
    public double getValue() {
      return value_;
    }

    private void initFields() {
      position_ = 0L;
      value_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, position_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, position_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.rice.pdb.serialization.proto.LongVectorP}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.rice.pdb.serialization.proto.LongVectorP)
        edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorPOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.rice.pdb.serialization.proto.LongVectorProtos.internal_static_edu_rice_pdb_serialization_proto_LongVectorP_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.rice.pdb.serialization.proto.LongVectorProtos.internal_static_edu_rice_pdb_serialization_proto_LongVectorP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP.class, edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP.Builder.class);
      }

      // Construct using edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        position_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.rice.pdb.serialization.proto.LongVectorProtos.internal_static_edu_rice_pdb_serialization_proto_LongVectorP_descriptor;
      }

      public edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP getDefaultInstanceForType() {
        return edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP.getDefaultInstance();
      }

      public edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP build() {
        edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP buildPartial() {
        edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP result = new edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.position_ = position_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP) {
          return mergeFrom((edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP other) {
        if (other == edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP.getDefaultInstance()) return this;
        if (other.hasPosition()) {
          setPosition(other.getPosition());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPosition()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.rice.pdb.serialization.proto.LongVectorProtos.LongVectorP) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long position_ ;
      /**
       * <code>required fixed64 position = 1;</code>
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required fixed64 position = 1;</code>
       */
      public long getPosition() {
        return position_;
      }
      /**
       * <code>required fixed64 position = 1;</code>
       */
      public Builder setPosition(long value) {
        bitField0_ |= 0x00000001;
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 position = 1;</code>
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000001);
        position_ = 0L;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>required double value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double value = 2;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>required double value = 2;</code>
       */
      public Builder setValue(double value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:edu.rice.pdb.serialization.proto.LongVectorP)
    }

    static {
      defaultInstance = new LongVectorP(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:edu.rice.pdb.serialization.proto.LongVectorP)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_rice_pdb_serialization_proto_LongVectorP_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_rice_pdb_serialization_proto_LongVectorP_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020LongVector.proto\022 edu.rice.pdb.seriali" +
      "zation.proto\".\n\013LongVectorP\022\020\n\010position\030" +
      "\001 \002(\006\022\r\n\005value\030\002 \002(\001B4\n edu.rice.pdb.ser" +
      "ialization.protoB\020LongVectorProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_edu_rice_pdb_serialization_proto_LongVectorP_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_rice_pdb_serialization_proto_LongVectorP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_edu_rice_pdb_serialization_proto_LongVectorP_descriptor,
        new java.lang.String[] { "Position", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
