// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Part.proto

package edu.rice.pdb.serialization.proto;

public final class PartProtos {
  private PartProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.rice.pdb.serialization.proto.Part)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 partID = 1;</code>
     */
    boolean hasPartID();
    /**
     * <code>required int32 partID = 1;</code>
     */
    int getPartID();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string mfgr = 3;</code>
     */
    boolean hasMfgr();
    /**
     * <code>required string mfgr = 3;</code>
     */
    java.lang.String getMfgr();
    /**
     * <code>required string mfgr = 3;</code>
     */
    com.google.protobuf.ByteString
        getMfgrBytes();

    /**
     * <code>required string brand = 4;</code>
     */
    boolean hasBrand();
    /**
     * <code>required string brand = 4;</code>
     */
    java.lang.String getBrand();
    /**
     * <code>required string brand = 4;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>required string type = 5;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 5;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 5;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>required int32 size = 6;</code>
     */
    boolean hasSize();
    /**
     * <code>required int32 size = 6;</code>
     */
    int getSize();

    /**
     * <code>required string container = 7;</code>
     */
    boolean hasContainer();
    /**
     * <code>required string container = 7;</code>
     */
    java.lang.String getContainer();
    /**
     * <code>required string container = 7;</code>
     */
    com.google.protobuf.ByteString
        getContainerBytes();

    /**
     * <code>required double retailPrice = 8;</code>
     */
    boolean hasRetailPrice();
    /**
     * <code>required double retailPrice = 8;</code>
     */
    double getRetailPrice();

    /**
     * <code>required string comment = 9;</code>
     */
    boolean hasComment();
    /**
     * <code>required string comment = 9;</code>
     */
    java.lang.String getComment();
    /**
     * <code>required string comment = 9;</code>
     */
    com.google.protobuf.ByteString
        getCommentBytes();
  }
  /**
   * Protobuf type {@code edu.rice.pdb.serialization.proto.Part}
   */
  public static final class Part extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:edu.rice.pdb.serialization.proto.Part)
      PartOrBuilder {
    // Use Part.newBuilder() to construct.
    private Part(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Part(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Part defaultInstance;
    public static Part getDefaultInstance() {
      return defaultInstance;
    }

    public Part getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Part(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              partID_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              mfgr_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              brand_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              type_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              size_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              container_ = bs;
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              retailPrice_ = input.readDouble();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              comment_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.rice.pdb.serialization.proto.PartProtos.internal_static_edu_rice_pdb_serialization_proto_Part_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.rice.pdb.serialization.proto.PartProtos.internal_static_edu_rice_pdb_serialization_proto_Part_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.rice.pdb.serialization.proto.PartProtos.Part.class, edu.rice.pdb.serialization.proto.PartProtos.Part.Builder.class);
    }

    public static com.google.protobuf.Parser<Part> PARSER =
        new com.google.protobuf.AbstractParser<Part>() {
      public Part parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Part(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Part> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PARTID_FIELD_NUMBER = 1;
    private int partID_;
    /**
     * <code>required int32 partID = 1;</code>
     */
    public boolean hasPartID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 partID = 1;</code>
     */
    public int getPartID() {
      return partID_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MFGR_FIELD_NUMBER = 3;
    private java.lang.Object mfgr_;
    /**
     * <code>required string mfgr = 3;</code>
     */
    public boolean hasMfgr() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string mfgr = 3;</code>
     */
    public java.lang.String getMfgr() {
      java.lang.Object ref = mfgr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mfgr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string mfgr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMfgrBytes() {
      java.lang.Object ref = mfgr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mfgr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRAND_FIELD_NUMBER = 4;
    private java.lang.Object brand_;
    /**
     * <code>required string brand = 4;</code>
     */
    public boolean hasBrand() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string brand = 4;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          brand_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string brand = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private java.lang.Object type_;
    /**
     * <code>required string type = 5;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string type = 5;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 6;
    private int size_;
    /**
     * <code>required int32 size = 6;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 size = 6;</code>
     */
    public int getSize() {
      return size_;
    }

    public static final int CONTAINER_FIELD_NUMBER = 7;
    private java.lang.Object container_;
    /**
     * <code>required string container = 7;</code>
     */
    public boolean hasContainer() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string container = 7;</code>
     */
    public java.lang.String getContainer() {
      java.lang.Object ref = container_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          container_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string container = 7;</code>
     */
    public com.google.protobuf.ByteString
        getContainerBytes() {
      java.lang.Object ref = container_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        container_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETAILPRICE_FIELD_NUMBER = 8;
    private double retailPrice_;
    /**
     * <code>required double retailPrice = 8;</code>
     */
    public boolean hasRetailPrice() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required double retailPrice = 8;</code>
     */
    public double getRetailPrice() {
      return retailPrice_;
    }

    public static final int COMMENT_FIELD_NUMBER = 9;
    private java.lang.Object comment_;
    /**
     * <code>required string comment = 9;</code>
     */
    public boolean hasComment() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string comment = 9;</code>
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          comment_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string comment = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      partID_ = 0;
      name_ = "";
      mfgr_ = "";
      brand_ = "";
      type_ = "";
      size_ = 0;
      container_ = "";
      retailPrice_ = 0D;
      comment_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPartID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMfgr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBrand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContainer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRetailPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasComment()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, partID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMfgrBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getBrandBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, size_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getContainerBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, retailPrice_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getCommentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, partID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMfgrBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getBrandBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, size_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getContainerBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, retailPrice_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getCommentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.rice.pdb.serialization.proto.PartProtos.Part parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.rice.pdb.serialization.proto.PartProtos.Part parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.rice.pdb.serialization.proto.PartProtos.Part parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.rice.pdb.serialization.proto.PartProtos.Part parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.rice.pdb.serialization.proto.PartProtos.Part parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.rice.pdb.serialization.proto.PartProtos.Part parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.rice.pdb.serialization.proto.PartProtos.Part parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.rice.pdb.serialization.proto.PartProtos.Part parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.rice.pdb.serialization.proto.PartProtos.Part parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.rice.pdb.serialization.proto.PartProtos.Part parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.rice.pdb.serialization.proto.PartProtos.Part prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.rice.pdb.serialization.proto.Part}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.rice.pdb.serialization.proto.Part)
        edu.rice.pdb.serialization.proto.PartProtos.PartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.rice.pdb.serialization.proto.PartProtos.internal_static_edu_rice_pdb_serialization_proto_Part_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.rice.pdb.serialization.proto.PartProtos.internal_static_edu_rice_pdb_serialization_proto_Part_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.rice.pdb.serialization.proto.PartProtos.Part.class, edu.rice.pdb.serialization.proto.PartProtos.Part.Builder.class);
      }

      // Construct using edu.rice.pdb.serialization.proto.PartProtos.Part.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        partID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        mfgr_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        brand_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        container_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        retailPrice_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        comment_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.rice.pdb.serialization.proto.PartProtos.internal_static_edu_rice_pdb_serialization_proto_Part_descriptor;
      }

      public edu.rice.pdb.serialization.proto.PartProtos.Part getDefaultInstanceForType() {
        return edu.rice.pdb.serialization.proto.PartProtos.Part.getDefaultInstance();
      }

      public edu.rice.pdb.serialization.proto.PartProtos.Part build() {
        edu.rice.pdb.serialization.proto.PartProtos.Part result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.rice.pdb.serialization.proto.PartProtos.Part buildPartial() {
        edu.rice.pdb.serialization.proto.PartProtos.Part result = new edu.rice.pdb.serialization.proto.PartProtos.Part(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.partID_ = partID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mfgr_ = mfgr_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.brand_ = brand_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.container_ = container_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.retailPrice_ = retailPrice_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.comment_ = comment_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.rice.pdb.serialization.proto.PartProtos.Part) {
          return mergeFrom((edu.rice.pdb.serialization.proto.PartProtos.Part)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.rice.pdb.serialization.proto.PartProtos.Part other) {
        if (other == edu.rice.pdb.serialization.proto.PartProtos.Part.getDefaultInstance()) return this;
        if (other.hasPartID()) {
          setPartID(other.getPartID());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasMfgr()) {
          bitField0_ |= 0x00000004;
          mfgr_ = other.mfgr_;
          onChanged();
        }
        if (other.hasBrand()) {
          bitField0_ |= 0x00000008;
          brand_ = other.brand_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000010;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasContainer()) {
          bitField0_ |= 0x00000040;
          container_ = other.container_;
          onChanged();
        }
        if (other.hasRetailPrice()) {
          setRetailPrice(other.getRetailPrice());
        }
        if (other.hasComment()) {
          bitField0_ |= 0x00000100;
          comment_ = other.comment_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPartID()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasMfgr()) {
          
          return false;
        }
        if (!hasBrand()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasSize()) {
          
          return false;
        }
        if (!hasContainer()) {
          
          return false;
        }
        if (!hasRetailPrice()) {
          
          return false;
        }
        if (!hasComment()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.rice.pdb.serialization.proto.PartProtos.Part parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.rice.pdb.serialization.proto.PartProtos.Part) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int partID_ ;
      /**
       * <code>required int32 partID = 1;</code>
       */
      public boolean hasPartID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 partID = 1;</code>
       */
      public int getPartID() {
        return partID_;
      }
      /**
       * <code>required int32 partID = 1;</code>
       */
      public Builder setPartID(int value) {
        bitField0_ |= 0x00000001;
        partID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 partID = 1;</code>
       */
      public Builder clearPartID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        partID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mfgr_ = "";
      /**
       * <code>required string mfgr = 3;</code>
       */
      public boolean hasMfgr() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string mfgr = 3;</code>
       */
      public java.lang.String getMfgr() {
        java.lang.Object ref = mfgr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mfgr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string mfgr = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMfgrBytes() {
        java.lang.Object ref = mfgr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mfgr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string mfgr = 3;</code>
       */
      public Builder setMfgr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mfgr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string mfgr = 3;</code>
       */
      public Builder clearMfgr() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mfgr_ = getDefaultInstance().getMfgr();
        onChanged();
        return this;
      }
      /**
       * <code>required string mfgr = 3;</code>
       */
      public Builder setMfgrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mfgr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object brand_ = "";
      /**
       * <code>required string brand = 4;</code>
       */
      public boolean hasBrand() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string brand = 4;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            brand_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string brand = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string brand = 4;</code>
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 4;</code>
       */
      public Builder clearBrand() {
        bitField0_ = (bitField0_ & ~0x00000008);
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 4;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        brand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 5;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string type = 5;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 5;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 5;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 5;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>required int32 size = 6;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 size = 6;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>required int32 size = 6;</code>
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000020;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 size = 6;</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000020);
        size_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object container_ = "";
      /**
       * <code>required string container = 7;</code>
       */
      public boolean hasContainer() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string container = 7;</code>
       */
      public java.lang.String getContainer() {
        java.lang.Object ref = container_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            container_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string container = 7;</code>
       */
      public com.google.protobuf.ByteString
          getContainerBytes() {
        java.lang.Object ref = container_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          container_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string container = 7;</code>
       */
      public Builder setContainer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        container_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string container = 7;</code>
       */
      public Builder clearContainer() {
        bitField0_ = (bitField0_ & ~0x00000040);
        container_ = getDefaultInstance().getContainer();
        onChanged();
        return this;
      }
      /**
       * <code>required string container = 7;</code>
       */
      public Builder setContainerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        container_ = value;
        onChanged();
        return this;
      }

      private double retailPrice_ ;
      /**
       * <code>required double retailPrice = 8;</code>
       */
      public boolean hasRetailPrice() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required double retailPrice = 8;</code>
       */
      public double getRetailPrice() {
        return retailPrice_;
      }
      /**
       * <code>required double retailPrice = 8;</code>
       */
      public Builder setRetailPrice(double value) {
        bitField0_ |= 0x00000080;
        retailPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double retailPrice = 8;</code>
       */
      public Builder clearRetailPrice() {
        bitField0_ = (bitField0_ & ~0x00000080);
        retailPrice_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object comment_ = "";
      /**
       * <code>required string comment = 9;</code>
       */
      public boolean hasComment() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string comment = 9;</code>
       */
      public java.lang.String getComment() {
        java.lang.Object ref = comment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            comment_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string comment = 9;</code>
       */
      public com.google.protobuf.ByteString
          getCommentBytes() {
        java.lang.Object ref = comment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string comment = 9;</code>
       */
      public Builder setComment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        comment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string comment = 9;</code>
       */
      public Builder clearComment() {
        bitField0_ = (bitField0_ & ~0x00000100);
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      /**
       * <code>required string comment = 9;</code>
       */
      public Builder setCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        comment_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:edu.rice.pdb.serialization.proto.Part)
    }

    static {
      defaultInstance = new Part(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:edu.rice.pdb.serialization.proto.Part)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_rice_pdb_serialization_proto_Part_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_rice_pdb_serialization_proto_Part_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nPart.proto\022 edu.rice.pdb.serialization" +
      ".proto\"\226\001\n\004Part\022\016\n\006partID\030\001 \002(\005\022\014\n\004name\030" +
      "\002 \002(\t\022\014\n\004mfgr\030\003 \002(\t\022\r\n\005brand\030\004 \002(\t\022\014\n\004ty" +
      "pe\030\005 \002(\t\022\014\n\004size\030\006 \002(\005\022\021\n\tcontainer\030\007 \002(" +
      "\t\022\023\n\013retailPrice\030\010 \002(\001\022\017\n\007comment\030\t \002(\tB" +
      ".\n edu.rice.pdb.serialization.protoB\nPar" +
      "tProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_edu_rice_pdb_serialization_proto_Part_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_rice_pdb_serialization_proto_Part_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_edu_rice_pdb_serialization_proto_Part_descriptor,
        new java.lang.String[] { "PartID", "Name", "Mfgr", "Brand", "Type", "Size", "Container", "RetailPrice", "Comment", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
